// Sends one sample of each platform email style to an address, to eyeball the branded template.
// Usage: npm run mail:samples -- you@example.com
import { sendEmail, appUrl, type Sender } from "@/lib/mail/mailer";
import { renderSummaryHtml } from "@/domains/organizations/dailySummaryService";
import { ExecutiveDigestService } from "@/domains/platform/executiveDigestService";
import { mtag, mh, mp, mlinks, mtable, mbtn, mfine, mcallout, mfacts, mquote } from "@/lib/mail/layout";

const to = process.argv[2];
if (!to) throw new Error("usage: npm run mail:samples -- <email>");

const samples: { from: Sender; subject: string; preheader: string; html: string }[] = [
  { from: "billing", subject: "[Sample] Ridhzo tax invoice INV-0001 — ₹1,180", preheader: "Payment received", html: mh("Payment received — thank you") + mp("Your GST tax invoice is ready to view and download.") + mfacts([["Invoice number", "INV-0001"], ["Amount (incl. GST)", "₹1,180.00"]]) + mbtn("View invoice", appUrl("/settings/billing")) + mfine("You're getting this because this address is set for invoices.") },
  { from: "billing", subject: "[Sample] Payment failed for Acme — Grace period active", preheader: "Update your payment method", html: mh("Subscription payment failed") + mp("We couldn't process the recurring payment for your <strong>Pro</strong> plan on <strong>Acme</strong>.") + mcallout("<strong>Reason:</strong> Card declined<br><strong>Grace Period:</strong> fully operational until <strong>Oct 7, 2026</strong>.", "warn") + mbtn("Update payment method", appUrl("/settings/billing")) },
  { from: "noreply", subject: "[Sample] Reset your Ridhzo password", preheader: "Valid for 1 hour", html: mh("Reset your password") + mp("Hi Naveen,") + mp("We received a request to reset your password.") + mbtn("Reset password", appUrl("/reset-password/x")) + mfine("This link is valid for 1 hour. Didn't ask for this? Ignore this email.") },
  { from: "noreply", subject: "[Sample] You've been invited to Acme", preheader: "Join Acme on Ridhzo", html: mh("You're invited to join Acme") + mp("Collaborate on leads with your team in Ridhzo.") + mbtn("Accept invitation", appUrl("/invite/x")) + mfine("This invitation expires in 7 days.") },
  { from: "notifications", subject: "[Sample] New lead assigned to you", preheader: "Priya Sharma (Acme Traders)", html: mh("New lead assigned to you") + mp("Priya Sharma (Acme Traders) was just assigned to you.") + mbtn("Open in Ridhzo", appUrl("/leads")) },
  { from: "hello", subject: "[Sample] Support update", preheader: "We've looked into this", html: mh("Support update") + mp("Your ticket was updated.") + mquote("Thanks for reaching out — this is fixed now.") + mbtn("Open your support requests", appUrl("/settings/support")) },
  { from: "hello", subject: "[Sample] Data retention expiry notice", preheader: "Acme data will be anonymized", html: mh("Data retention expiry notice") + mp("Your organization <strong>Acme</strong> has been suspended for 60 days.") + mcallout("All customer records will be permanently anonymized in <strong>30 days</strong>.", "danger") + mbtn("Contact support", "mailto:hello@ridhzo.com") },
  { from: "notifications", subject: "[Sample] Overdue follow-up: Priya Sharma", preheader: "Call Priya about the quote", html: mtag("Overdue follow-up", "danger") + mh("Overdue follow-up: Priya Sharma") + mp("Call Priya about the quote — it was due 2 hours ago.") + mbtn("Follow up now", appUrl("/follow-ups")) + mfine("The sooner you follow up, the better the chance of winning the lead.") },
  { from: "notifications", subject: "[Sample] Follow-up due: Rahul Verma", preheader: "Due at 4:00 PM", html: mtag("Follow-up due", "warn") + mh("Follow-up due: Rahul Verma") + mp("Send the revised proposal — due at 4:00 PM today.") + mbtn("Open follow-up", appUrl("/follow-ups")) },
  { from: "notifications", subject: "[Sample] Today at Acme: 3 overdue follow-ups · 2 meetings today", preheader: "Your team's day at a glance", html: renderSummaryHtml("Acme Traders", { overdueFollowUps: 3, meetingsNeedOutcome: 1, meetingsToday: 2, newLeads: 5, uncontactedLeads: 2, unassignedLeads: 1, byRep: [{ name: "Ravi", overdue: 3, needOutcome: 1 }], calls: [{ name: "Priya", calls: 34, attempts: 30, answered: 21, talkSec: 5400 }], people: [] }) },
  { from: "notifications", subject: "[Sample] Executive briefing", preheader: "Weekly platform overview", html: ExecutiveDigestService.renderDigestHtml({ generatedAt: new Date().toISOString(), frequency: "weekly", metrics: { totalOrgs: 42, totalLeads: 18250, totalUsers: 120, dbHealthy: true, failedDeliveries: 2 } as any, revops: { arr: 1500000, mrr: 125000, arpu: 2976, paidAccounts: 30, freeAccounts: 12 } as any, openTicketsCount: 3, atRiskTenants: [{ name: "Acme Corp", plan: "pro", daysInactive: 21, health: "critical" } as any] }) },
  { from: "notifications", subject: "[Sample] Overdue follow-up: Priya Sharma (with lead context)", preheader: "Call Priya about the quote", html: mtag("Overdue follow-up", "danger") + mh("Overdue follow-up: Priya Sharma") + mp("Call Priya about the quote — it was due 2 hours ago.") + mfacts([["Name", "Priya Sharma"], ["Company", "Acme Traders"], ["Phone", "98765 43210"], ["Email", "priya@acme.example"]]) + mlinks([["📞 Call", "tel:+919876543210"], ["💬 WhatsApp", "https://wa.me/919876543210"]]) + mbtn("Follow up now", appUrl("/follow-ups")) + mfine("The sooner you follow up, the better the chance of winning the lead.") },
  { from: "hello", subject: "[Sample] Welcome to Ridhzo, Naveen — your workspace is ready", preheader: "Three quick steps", html: mtag("Welcome", "ok") + mh("Your workspace “Acme Traders” is ready") + mp("Hi Naveen, welcome to Ridhzo — leads move faster here. Three steps to get going:") + mtable(["Step", "What to do"], [["<strong>1. Add leads</strong>", "Import a CSV, connect a lead source or add one by hand."], ["<strong>2. Invite your team</strong>", "Add teammates so leads get assigned and followed up."], ["<strong>3. Set follow-ups</strong>", "Never lose a lead — every lead gets a next step and a reminder."]]) + mbtn("Open your workspace", appUrl("/")) + mfine("Need a hand? Just reply to this email.") },
];

(async () => {
  for (const s of samples) { await sendEmail({ ...s, to }); console.log("sent:", s.subject); await new Promise((r) => setTimeout(r, 600)); }
})();
