// The full set of `action` strings AuditService.log is ever called with, plus a short label for
// each — used to populate the action filter on /settings/audit. Client-safe (no `db` import), so
// it can be imported directly by the client-side table component.
//
// Keep this in sync with the call sites: it's a UI convenience (a filter dropdown), not an
// enforced enum — AuditService.log accepts any string, so this list can lag a newly added call
// site without anything breaking; it just won't be filterable until added here.
export const AUDIT_ACTIONS: { value: string; label: string }[] = [
  { value: "integration.whatsapp_connect", label: "WhatsApp account connected" },
  { value: "integration.whatsapp_disconnect", label: "WhatsApp account disconnected" },
  { value: "integration.whatsapp_token_rotate", label: "WhatsApp webhook URL rotated" },
  { value: "billing.payment_attempt_failed", label: "Payment attempt failed" },
  { value: "billing.partial_refund", label: "Partial refund received" },
  { value: "user.login_failed", label: "Failed sign-in" },
  { value: "user.logout", label: "Signed out" },
  { value: "lead.create", label: "Lead created" },
  { value: "lead.status_change", label: "Lead status changed" },
  { value: "lead.bulk_status_change", label: "Leads bulk status change" },
  { value: "lead.assign", label: "Lead assigned" },
  { value: "lead.bulk_assign", label: "Leads bulk-assigned" },
  { value: "lead.import", label: "Leads imported" },
  { value: "source.create", label: "Source created" },
  { value: "source.activate", label: "Source activated" },
  { value: "source.pause", label: "Source paused" },
  { value: "source.delete", label: "Source deleted" },
  { value: "webhook.create", label: "Webhook created" },
  { value: "webhook.activate", label: "Webhook activated" },
  { value: "webhook.pause", label: "Webhook paused" },
  { value: "webhook.delete", label: "Webhook deleted" },
  { value: "distribution_rule.create", label: "Distribution rule created" },
  { value: "distribution_rule.update", label: "Distribution rule updated" },
  { value: "distribution_rule.delete", label: "Distribution rule deleted" },
  { value: "integration.enrichment_update", label: "Enrichment settings updated" },
  { value: "integration.enrichment_disconnect", label: "Enrichment disconnected" },
  { value: "integration.capi_update", label: "Meta CAPI settings updated" },
  { value: "integration.capi_disconnect", label: "Meta CAPI disconnected" },
  { value: "integration.capi_stage_map", label: "Meta CAPI stage map updated" },
  { value: "integration.inbound_email_set", label: "Inbound email toggled" },
  { value: "integration.inbound_token_rotate", label: "Inbound email token rotated" },
  { value: "status.upsert", label: "Lead status added/edited" },
  { value: "status.delete", label: "Lead status deleted" },
  { value: "ai_agent.change_status", label: "AI assistant changed a status" },
  { value: "ai_agent.add_tag", label: "AI assistant added a tag" },
  { value: "ai_agent.set_reminder", label: "AI assistant set a reminder" },
  { value: "ai_agent.schedule_meeting", label: "AI assistant booked a meeting" },
  { value: "ai_agent.assign_lead", label: "AI assistant assigned a lead" },
  { value: "user.create", label: "User created" },
  { value: "user.invite", label: "User invited" },
  { value: "user.invite_accepted", label: "Invitation accepted" },
  { value: "invitation.revoke", label: "Invitation revoked" },
  { value: "user.role_change", label: "User role changed" },
  { value: "user.delete", label: "User deleted" },
  { value: "user.activate", label: "User reactivated" },
  { value: "user.deactivate", label: "User deactivated" },
  { value: "role.create", label: "Role created" },
  { value: "role.update", label: "Role permissions changed" },
  { value: "role.delete", label: "Role deleted" },
  { value: "api_key.create", label: "API key created" },
  { value: "api_key.revoke", label: "API key revoked" },
  { value: "api_key.delete", label: "API key deleted" },
  { value: "lead.delete", label: "Lead deleted" },
  { value: "lead.bulk_delete", label: "Leads bulk-deleted" },
  { value: "lead.restore", label: "Lead restored" },
  { value: "lead.purge", label: "Lead purged" },
  { value: "lead.auto_purge", label: "Leads auto-purged (recycle bin)" },
  { value: "lead.recycle_bin.empty", label: "Recycle bin emptied" },
  { value: "lead.merge", label: "Leads merged" },
  { value: "lead.auto_merge", label: "Leads auto-merged" },
  { value: "lead.sla_escalated", label: "Lead SLA escalated" },
  { value: "billing.subscribe_start", label: "Subscription checkout started" },
  { value: "billing.subscribe_activate", label: "Subscription activated" },
  { value: "billing.plan_set_manual", label: "Plan set manually" },
  { value: "billing.plan_changed", label: "Plan changed (billing provider)" },
  { value: "billing.cancel", label: "Subscription cancelled" },
  { value: "org.settings_update", label: "Organization settings updated" },
  { value: "org.auto_merge_toggle", label: "Auto-merge duplicates toggled" },
  { value: "platform.set_plan", label: "Platform: plan set" },
  { value: "platform.suspend", label: "Platform: organization suspended" },
  { value: "platform.reactivate", label: "Platform: organization reactivated" },
  { value: "platform.impersonate_start", label: "Platform: impersonation started" },
  { value: "platform.impersonate_stop", label: "Platform: impersonation stopped" },
  { value: "webhook.secret_reveal", label: "Webhook secret revealed" },
];
