// Writes docs/DATABASE.md from a live, migrated Postgres:  DATABASE_URL=... node scripts/gen-db-doc.mjs
import postgres from "postgres";
import { writeFileSync } from "node:fs";
const sql = postgres(process.env.DATABASE_URL);
const cols = await sql`select table_name t, column_name c, data_type d, is_nullable n from information_schema.columns where table_schema='public' order by table_name, ordinal_position`;
const fks = await sql`select conrelid::regclass::text t, pg_get_constraintdef(oid) d from pg_constraint where contype='f' and connamespace='public'::regnamespace order by 1`;
const by = Object.groupBy(cols, (r) => r.t);
let md = "# Database reference\n\nGenerated by `node scripts/gen-db-doc.mjs` from the migrated schema — do not edit by hand. Every tenant table carries `organization_id` (NOT NULL).\n\n## Foreign keys\n\n" + fks.map((f) => `- \`${f.t}\` ${f.d}`).join("\n") + "\n";
for (const [t, cs] of Object.entries(by)) md += `\n## ${t}\n\n| column | type | null |\n|---|---|---|\n` + cs.map((c) => `| ${c.c} | ${c.d} | ${c.n === "YES" ? "yes" : ""} |`).join("\n") + "\n";
writeFileSync("docs/DATABASE.md", md);
await sql.end();
console.log(`wrote docs/DATABASE.md (${Object.keys(by).length} tables)`);
